### ISSUE TITLE
addClass and removeClass 简单方法 

### ISSUE THREAD

**Issue by CntChen** [vincent-zheng/miniJQuery#1]
可以看下以下方法是不是正确的，感觉在单个DOM add/remove 单个Class 的时候，该方法简单一点 
>    trim = function(str)
    {
        return str.trim ? str.trim() : str.replace(/^\s+|\s+$/g,'');
    },
    hasClass = function(el, cn)
    {
        return (' ' + el.className + ' ').indexOf(' ' + cn + ' ') !== -1;
    },
    addClass = function(el, cn)
    {
        if (!hasClass(el, cn)) {
            el.className = (el.className === '') ? cn : el.className + ' ' + cn;
        }
    },
    removeClass = function(el, cn)
    {
        el.className = trim((' ' + el.className + ' ').replace(' ' + cn + ' ', ' '));
    },

**Comment by vincent-zheng** [comment]
### 关于addClass那部分的
你这样做的目的是为了去除重复的class？我感觉是有点多余的，因为浏览器在发现dom上有多个相同的class的时候会自己去重的，所以应该将这部分交给浏览器自己来处理，而我这边只需要负责将class添加上去就可以了，而不需要做这么多判断出来。
### 关于removeClass这部分
这部分的确是可以考虑直接使用正则去的，你这样做应该比我现在的方法要好点，不过那个trim有点多余，感觉。可以改成用正则来去掉class，我现在过去改一下，你可以过来看一下。

**Comment by CUNTIE** [comment]
## 关于 addClass ##
原来浏览器是可以自动处理的 [赞]

## 关于 removeClass ##
> trim((' ' + el.className + ' ').replace(' ' + cn + ' ', ' '));

等同于：
>(' ' + el.className + ' ').replace(' ' + cn + ' ', ' ').replace(/^\s+|\s+$/g, '');

主要处理 **一个 class的name是另一个class name一部分** 的情况, 给每个 class name **添加空格作为边界**来避免误判

例如

    <a href="#" class="link activelink"></a>

正则全局替换 **'link'** 则会得到 class=“active”

**Comment by vincent-zheng** [comment]
把函数方法换成了，你那里会在"link"这样的时候无法removeclass
```
dom.className = dom.className.replace(new RegExp('\\b' + className + '\\b', "g"), '');
```
